import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * サイドバーを作成することで、以下のことが可能になります：
 * - ドキュメントの順序付けられたグループを作成
 * - そのグループの各ドキュメントにサイドバーを表示
 * - 次/前のナビゲーションを提供
 *
 * サイドバーはファイルシステムから自動生成するか、
 * このファイルで明示的に定義することができます。
 *
 * 必要な数だけサイドバーを作成できます。
 */
const sidebars: SidebarsConfig = {
  serviceSidebar: [{ type: "autogenerated", dirName: "service" }],
  developmentSidebar: [{ type: "autogenerated", dirName: "development" }],
  openApiSidebar: [
    {
      type: "category",
      label: "Petstore",
      link: {
        type: "generated-index",
        title: "Petstore API",
        description:
          "This is a sample server Petstore server. You can find out more about Swagger at http://swagger.io or on irc.freenode.net, #swagger. For this sample, you can use the api key special-key to test the authorization filters.",
        slug: "/api/petstore-api",
      },
      items: require("./docs/petstore/sidebar.ts"),
    },
  ],
};

export default sidebars;
