name: Build Docusaurus

on:
  pull_request:
    branches:
      - main

jobs:
  build-docusaurus:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
        with:
          path: docs
      - run: npm run build --prefix=docs
